services:
  crawler:
    build: ./crawler      # 使用自定义镜像
    container_name: crawler_rainbowow
    volumes:
      - ./crawler:/app     # 挂载代码目录
    working_dir: /app
    command: ["sleep", "infinity"]
    depends_on:
      - redis
      - mongodb
    environment:
      - DISPLAY=${DISPLAY}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DB=${MONGO_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - TZ=${TZ}
    networks:
      - rainbow_net

  cli:
    build: ./cli      # 使用自定义镜像
    container_name: cli_rainbowow
    volumes:
      - ./cli:/app     # 挂载代码目录
    working_dir: /app
    command: ["sleep", "infinity"]
    depends_on:
      - redis
      - mongodb
    environment:
      - DISPLAY=${DISPLAY}
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DB=${MONGO_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - TZ=${TZ}
    networks:
      - rainbow_net

  webui:
    build: ./webui
    container_name: webui_rainbowow
    ports:
      - "8600:8000"
    depends_on:
      - redis
      - mongodb
    environment:
      - MONGO_HOST=${MONGO_HOST}
      - MONGO_PORT=${MONGO_PORT}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASS=${MONGO_PASS}
      - MONGO_DB=${MONGO_DB}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - TZ=${TZ}
    networks:
      - rainbow_net
    
  redis:
    image: redis:7-alpine
    container_name: redis_rainbowow
    ports:
      - "6390:6379"               # 可选，暴露给宿主机
    volumes:
      - ./data/redis:/data        # Redis 持久化
    command: redis-server --appendonly yes
    networks:
      - rainbow_net

  mongodb:
    image: mongo:8
    container_name: mongo_rainbowow
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db     # MongoDB 数据持久化
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    networks:
      - rainbow_net

networks:
  rainbow_net:
    driver: bridge